name: Generate Directory Structure

on:
    push:
        branches:
            - main

jobs:
    generate-directory-structure:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Generate Directory Structure
              id: generate-structure
              run: |
                tree -I '.git|.github' --dirsfirst > directory_structure.md
            
            - name: Format Directory Structure
              id: format-for-readme
              run: |
                content=$(cat directory_structure.md)
                echo "$content" | sed '1d' > CONTRIBUTING.md
            
            - name: Commit changes
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add CONTRIBUTING.md
                git commit -m "Add directory structure"
                git push origin main