name: Generate Directory Structure

on:
    push:
        branches:
            - main

jobs:
    generate-directory-structure:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Generate Directory Structure
              id: generate-structure
              run: |
                tree -I '.git|.github' --dirsfirst > directory_structure.md
                cat directory_structure.md
            
            - name: Commit changes
              run:
                git add directory_structure.md
                git commit
                git push